__author__ = 'rdiekema'

import fresh_tomatoes as ft
import media as media
import json


def main():
    movies = list()
    movies.append(media.Movie("https://upload.wikimedia.org/wikipedia/en/e/e7/Jurassic_Park_poster.jpg", "Jurassic Park", "https://www.youtube.com/watch?v=QWBKEmWWL38",'''{"Title":"Jurassic Park","Year":"1993","Rated":"PG-13","Released":"11 Jun 1993","Runtime":"127 min","Genre":"Adventure, Sci-Fi, Thriller","Director":"Steven Spielberg","Writer":"Michael Crichton (novel), Michael Crichton (screenplay), David Koepp (screenplay)","Actors":"Sam Neill, Laura Dern, Jeff Goldblum, Richard Attenborough","Plot":"During a preview tour, a theme park suffers a major power breakdown that allows its cloned dinosaur exhibits to run amok.","Language":"English, Spanish","Country":"USA","Awards":"Won 3 Oscars. Another 24 wins & 16 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_SX300.jpg","Metascore":"68","imdbRating":"8.1","imdbVotes":"518159","imdbID":"tt0107290","Type":"movie","Response":"True"}'''))
    movies.append(media.Movie("https://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg", "Toy Story", "https://www.youtube.com/watch?v=KYz2wyBy3kc",'''{"Title":"Toy Story","Year":"1995","Rated":"G","Released":"22 Nov 1995","Runtime":"81 min","Genre":"Animation, Adventure, Comedy","Director":"John Lasseter","Writer":"John Lasseter (original story by), Pete Docter (original story by), Andrew Stanton (original story by), Joe Ranft (original story by), Joss Whedon (screenplay), Andrew Stanton (screenplay), Joel Cohen (screenplay), Alec Sokolow (screenplay)","Actors":"Tom Hanks, Tim Allen, Don Rickles, Jim Varney","Plot":"A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.","Language":"English","Country":"USA","Awards":"Nominated for 3 Oscars. Another 23 wins & 14 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTgwMjI4MzU5N15BMl5BanBnXkFtZTcwMTMyNTk3OA@@._V1_SX300.jpg","Metascore":"92","imdbRating":"8.3","imdbVotes":"533250","imdbID":"tt0114709","Type":"movie","Response":"True"}'''))
    movies.append(media.Movie("https://upload.wikimedia.org/wikipedia/en/8/8e/Office_space_poster.jpg", "Office Space", "https://www.youtube.com/watch?v=3_fG_zLbBeU",'''{"Title":"Office Space","Year":"1999","Rated":"R","Released":"19 Feb 1999","Runtime":"89 min","Genre":"Comedy","Director":"Mike Judge","Writer":"Mike Judge (Milton animated shorts), Mike Judge (screenplay)","Actors":"Ron Livingston, Jennifer Aniston, David Herman, Ajay Naidu","Plot":"Three company workers who hate their jobs decide to rebel against their greedy boss.","Language":"English","Country":"USA","Awards":"2 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BOTA5MzQ3MzI1NV5BMl5BanBnXkFtZTgwNTcxNTYxMTE@._V1_SX300.jpg","Metascore":"68","imdbRating":"7.8","imdbVotes":"185123","imdbID":"tt0151804","Type":"movie","Response":"True"}'''))
    movies.append(media.Movie("https://upload.wikimedia.org/wikipedia/en/4/45/Spaceballs.jpg", "Spaceballs", "https://www.youtube.com/watch?v=uWVSVgU-I0s",'''{"Title":"Spaceballs","Year":"1987","Rated":"PG","Released":"24 Jun 1987","Runtime":"96 min","Genre":"Adventure, Comedy, Sci-Fi","Director":"Mel Brooks","Writer":"Mel Brooks, Thomas Meehan, Ronny Graham","Actors":"Mel Brooks, John Candy, Rick Moranis, Bill Pullman","Plot":"Planet Spaceball's President Skroob sends Lord Dark Helmet to steal Planet Druidia's abundant supply of air to replenish their own, and only Lone Starr can stop them.","Language":"English","Country":"USA","Awards":"1 win.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTM3Mzg0Mzc2NF5BMl5BanBnXkFtZTcwNDEwNTk0NA@@._V1_SX300.jpg","Metascore":"46","imdbRating":"7.1","imdbVotes":"124397","imdbID":"tt0094012","Type":"movie","Response":"True"}'''))
    movies.append(media.Movie("https://upload.wikimedia.org/wikipedia/en/7/7b/Blazing_saddles_movie_poster.jpg", "Blazing Saddles", "https://www.youtube.com/watch?v=VKayG1TrfuE",'''{"Title":"Blazing Saddles","Year":"1974","Rated":"R","Released":"7 Feb 1974","Runtime":"93 min","Genre":"Comedy, Western","Director":"Mel Brooks","Writer":"Mel Brooks (screenplay), Norman Steinberg (screenplay), Andrew Bergman (screenplay), Richard Pryor (screenplay), Alan Uger (screenplay), Andrew Bergman (story)","Actors":"Cleavon Little, Gene Wilder, Slim Pickens, Harvey Korman","Plot":"To ruin a western town, a corrupt political boss appoints a black sheriff, who promptly becomes his most formidable adversary.","Language":"English, Yiddish, German","Country":"USA","Awards":"Nominated for 3 Oscars. Another 2 wins & 2 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTcyMzQ0MjQ5MF5BMl5BanBnXkFtZTYwOTczNjA5._V1_SX300.jpg","Metascore":"N/A","imdbRating":"7.8","imdbVotes":"87456","imdbID":"tt0071230","Type":"movie","Response":"True"}'''))
    movies.append(media.Movie("https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg", "The Matrix", "https://www.youtube.com/watch?v=vKQi3bBA1y8",'''{"Title":"The Matrix","Year":"1999","Rated":"R","Released":"31 Mar 1999","Runtime":"136 min","Genre":"Action, Sci-Fi","Director":"Andy Wachowski, Lana Wachowski","Writer":"Andy Wachowski, Lana Wachowski","Actors":"Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving","Plot":"A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.","Language":"English","Country":"USA, Australia","Awards":"Won 4 Oscars. Another 33 wins & 40 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTkxNDYxOTA4M15BMl5BanBnXkFtZTgwNTk0NzQxMTE@._V1_SX300.jpg","Metascore":"73","imdbRating":"8.7","imdbVotes":"1065503","imdbID":"tt0133093","Type":"movie","Response":"True"}'''))
    ft.open_movies_page(movies)


if __name__ == '__main__': main()